### ISSUE TITLE
Set maximum rebooting nodes / semaphore

### ISSUE THREAD

**Issue by dghubble** [coreos/container-linux-update-operator#105]
Adding a `-max-rebooting-nodes` flag to `update-operator` would provide the analog to the `locksmithctl set-max N` semaphore count setting shown [here](https://github.com/coreos/locksmith#maximum-semaphore).

Outstanding question is are we ok with setting the default group's max rebooting nodes via a flag or do we want to block this on having a fully fledged reboot group design (where group config may include its own notion of max-reboot-nodes)

Addresses related issue: #91

**Comment by philips** [comment]
If we do this please make it a ConfigMap or something.

**Comment by dghubble** [comment]
Closing, I don't use or maintain this project anymore. :heart:
