### ISSUE TITLE
handle case when original locksmith is already running

### ISSUE THREAD

**Issue by sym3tri** [coreos/container-linux-update-operator#15]
what will klocksmith do in these cases?

**Comment by dghubble** [comment]
It sounds like this discussion landed on making disabling locksmith a requirement and documenting it.

Disabling locksmithd is now listed as a requirement on the top level README: `locksmithd.service systemd unit on each machine should be masked and stopped in systemd`. Tectonic now non-optionally disables locksmithd on all platforms as well. I think this can be closed. @sym3tri @philips

**Comment by sym3tri** [comment]
yup
