### ISSUE TITLE
CLUO not rebooting nodes

### ISSUE THREAD

**Issue by jpds** [coreos/container-linux-update-operator#171]
I have a Typhoon deployed, Kubernetes 1.9.1 cluster that is running with CLUO.

With the latest `1632.2.1` release of stable CoreOS, I can see the node labels go through the normal mark `SchedulingDisabled`, move containers, update, reboot cycle - but for some reason, the nodes aren't actually rebooting, the pods are just getting shuffled around the cluster from node to node.

If I wait for node to go to `SchedulingDisabled`, and SSH in and reboot the node, everything works as expected and the node comes back with the newer version.

However, the nodes don't get rebooted by the operator and the uptime shows that the node never rebooted.

**Comment by dghubble** [comment]
What version of CLUO? Note that v0.5.0 was released to address an issue where CLUO couldn't drain nodes in 1.9 clusters.

**Comment by jpds** [comment]
Looks like I was running `0.4.1`, closing this for now.
