### ISSUE TITLE
converting YAML to JSON: yaml: line 317: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by mikekuzak** [coreos/container-linux-update-operator#179]
Getting this error when trying to install on a K8s cluster

```
> kubectl create -f https://github.com/coreos/container-linux-update-operator/blob/master/examples/deploy/update-operator.yaml
error: error converting YAML to JSON: yaml: line 317: mapping values are not allowed in this context
```

Any advice ? Thanks

**Comment by sdemos** [comment]
It looks like you are trying to use the github html page instead of the raw yaml content. Try using `kubectl create -f https://raw.githubusercontent.com/coreos/container-linux-update-operator/master/examples/deploy/update-operator.yaml` instead.

**Comment by mikekuzak** [comment]
Kinda worked. Had to create first namespace:  

> reboot-coordinator

Now I'm getting following exceptions:

> Error running agent process: failed to set node info: unable to update node "my-coreos03": failed to get node "my-coreos03": nodes "my-coreos03" is forbidden: User "system:serviceaccount:reboot-coordinator:default" cannot get nodes at the cluster scope

Any specific permissions which need to be given ?

**Comment by mikekuzak** [comment]
Worked. Thx

**Comment by sdemos** [comment]
Awesome! Happy to help. If you have any other problems, please feel free to comment here again or open another bug.

**Comment by prathyushach25** [comment]
Hi, 
I am trying to create a pod on kubernetes. I don't know why for some reason I am getting this error
ERROR:: error: error parsing pod.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
as far as I have cross checked my yaml file I found it correct. Please suggest me for any changes to be made.
Here is my yaml file
pod.yaml
apiVersion: v1
kind: pod
metadata:
 name: pod-example
spec:
  containers:
    -name: pod-example
     image: "ubuntu:14.04"
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  restartpolicy: Never

Thanks in advance.

**Comment by krishna-mallepula** [comment]
error: error parsing redis-master-deployment.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context

Can any one help me?

**Comment by krishna-mallepula** [comment]
This my YAML file:

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

error: error parsing redis-master-deployment.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context

**Comment by pramodrj07** [comment]
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ubuntu-test
spec:
  selector:
    app: ubuntu-test
  servers:
    ports:
    - port: 10080
	  name: tcp 
	  protocol: TCP
    hosts:
  - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ubuntu-test-gatewayvs
spec:
  hosts:
  - "*"
  gateways:
  - ubuntu-test-gateway
  tcp:
  - match:
    - port: 10001
    route:
    - destination:
        selector: ubuntu-test
        port: 12221
EOF

OUTPUT: error: error parsing STDIN: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context


WOuld be great if you can help me.

**Comment by lucab** [comment]
Those are generic Kubernetes manifests with errors, not related to `container-linux-update-operator` nor to this bug. Locking the conversation to prevent further confusion.
