### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by schmitch** [coreos/container-linux-update-operator#180]
Hello would it be possible for you to release version 0.7 with the reboot window?

I think a lot of people awaiting this feature.

**Comment by sdemos** [comment]
It is definitely time to cut a new release for this. Thanks for letting us know! I just want to get one more pr in, which should happen very soon, then I'll cut the release and update you here.

**Comment by sdemos** [comment]
`v0.7.0` is released! See the release page for details - https://github.com/coreos/container-linux-update-operator/releases/tag/v0.7.0
