### ISSUE TITLE
error: error parsing pod.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by prathyushach25** [coreos/container-linux-update-operator#189]
Hi,
I am trying to create a pod on kubernetes. I don't know why for some reason I am getting this error
ERROR:: error: error parsing pod.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
as far as I have cross checked my yaml file I found it correct. Please suggest me for any changes to be made.
Here is my yaml file
pod.yaml
apiVersion: v1
kind: pod
metadata:
name: pod-example
spec:
containers:
-name: pod-example
image: "ubuntu:14.04"
command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
restartpolicy: Never

Thanks in advance.

**Comment by prathyushach25** [comment]
> Hi,
> I am trying to create a pod on kubernetes. I don't know why for some reason I am getting this error
> ERROR:: error: error parsing pod.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
> as far as I have cross checked my yaml file I found it correct. Please suggest me for any changes to be made.
> Here is my yaml file
> pod.yaml
> apiVersion: v1
> kind: pod
> metadata:
> name: pod-example
> spec:
> containers:
> -name: pod-example
> image: "ubuntu:14.04"
> command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
> restartpolicy: Never
> 
> Thanks in advance.

**Comment by dghubble** [comment]
What does this have to do with CLUO?

**Comment by prathyushach25** [comment]
sorry, I did not understand. could please explain me further more @dghubble

**Comment by dghubble** [comment]
The question is not related to container-linux-update-operator. Please close.

**Comment by Ravibabu547** [comment]
error: error parsing https://github.com/justmeandopensource/kubernetes/blob/master/dashboard/dashboard.yaml: error converting YAML to JSON: yaml: line 118: mapping values are not allowed in this context

**Comment by Ravibabu547** [comment]
iam geting this error any one can help ..

**Comment by lucab** [comment]
Everybody randomly ending up here via search engine: the error is a generic YAML parsing issue; please double-check your YAML document with a linter, as it is likely just a syntax error.

Closing this ticket and locking it to prevent attracting other unrelated follow-ups.
