### ISSUE TITLE
Operator should integrate with "cloudproviders" to update launch config for new workers

### ISSUE THREAD

**Issue by euank** [coreos/container-linux-update-operator#56]
The motivating example is an AWS Autoscaling Group.

When an ASG is created, it is created with a single configured version of Container Linux. The ASG will continue to launch that version even if all the other nodes have updated.

When the group scales up, having to do a update/reboot cycle is just unnecessary churn.

I propose that the update operator can be configured to upgrade such a launch group once a majority of the nodes have successfully updated to a newer version.

**Comment by lucab** [comment]
/cc @crawford @aaronlevy 
If I recall correctly, according to latest discussion we in fact don't want to touch the ASG userdata. An update/reboot cycle is employed in order to provision matching OS/docker/kubelet before letting a node join the cluster.

**Comment by aaronlevy** [comment]
> An update/reboot cycle is employed in order to provision matching OS/docker/kubelet before letting a node join the cluster.

That is the current plan. We would ideally not have to rely on cloud-provider specific mechanics for our upgrade process. There may be a day where it becomes unavoidable - but it's a risk both from permissions perspective, and complexity for every new provider we want to support.

**Comment by lucab** [comment]
For reference, we now install nodes with a bootstrapper which takes care of upgrading the node OS beforea new node joins the cluster. This still requires a reboot and the installer can opt out of this for testing purposes.
