### ISSUE TITLE
agent: detect whether locksmithd is enabled and act appropriately

### ISSUE THREAD

**Issue by euank** [coreos/container-linux-update-operator#58]
Act appropriately here can mean either turning off locksmithd or turning off itself and notifying the user via an annotation.

It's possible that behaviour should be configurable.

This issue is basically a conclusion to #15.

At this point I'm leaning towards it disabling locksmithd since the user has indicated they wish updates to be managed via this tool instead.

**Comment by dghubble** [comment]
Resolved in #15 by requiring lcoksmithd to be disabled and documenting it.
