### ISSUE TITLE
use a label to filter critical pods

### ISSUE THREAD

**Issue by mischief** [coreos/container-linux-update-operator#7]
we don't want to delete some critical pods like kube-scheduler, and currently that's done by not deleting anything in `kube-system`.

what's right right label? anything with `k8s-app` key?

from https://github.com/coreos-inc/klocksmith/pull/6#discussion_r83062141

**Comment by dghubble** [comment]
I don't think this is relevant anymore. @yifan-gu objections to closing?

**Comment by yifan-gu** [comment]
Closing it for you :)
