### ISSUE TITLE
operator: add support for configuring maintenance windows

### ISSUE THREAD

**Issue by alekssaul** [coreos/container-linux-update-operator#82]
Locksmith support utilization of maintenance windows; 
https://coreos.com/os/docs/latest/update-strategies.html#auto-updates-with-a-maintenance-window . 
Would be nice for update operator to support setting up maintenance window preferably via TPR setting.

**Comment by swestcott** [comment]
Agreed, this is key for us. In addition, being able to easily suspend/resume reboots is important too.

**Comment by sdemos** [comment]
Reboot windows are now supported in master (see #170). I'll update this issue and then close it out once a release is tagged that has this feature in it.

**Comment by schmitch** [comment]
is there an eta, when a new release is made? we actually **need** this feature.

**Comment by sdemos** [comment]
`v0.7.0` is released, with support for reboot windows! See the release page for details - https://github.com/coreos/container-linux-update-operator/releases/tag/v0.7.0
