### ISSUE TITLE
Pass an additional toleration to /bin/update-operator

### ISSUE THREAD

**Issue by TerraTech** [coreos/container-linux-update-operator#83]
The spec for container-linux-update-agent-ds includes a toleration for _node-role.kubernetes.io/master_, is it possible to specify additional tolerations that can be passed when update-operator is run for the generated update-agent Deployment spec?  I did not see a flag to do so.

In our case, we want to add: _node-role.kubernetes.io/lb_

Right now, we have to modify the running container-linux-update-agent-ds DaemonSet spec and manually add the additional toleration after terraforming a new cluster.

**Comment by TerraTech** [comment]
I have uploaded a v0.2.0 docker image at: https://quay.io/terratech/container-linux-update-operator:v0.2.0-at if you'd like to take it for a test drive.

As an aside, are there plans to make the tags consistent where the Deployment uses ':v0.2.0' and the DaemonSet uses ':0.2.0'? It would be nice if semver had allowed for the 'v' prefix.  A simple fix would be to patch up: agentImageName() https://github.com/coreos/container-linux-update-operator/blob/master/pkg/operator/agent_manager.go#L222 and prefix it ```"%s-v%s"```.  The tag difference also affects build/build-image.sh.

**Comment by euank** [comment]
> Right now, we have to modify the running container-linux-update-agent-ds

What I expected for this case would be flipping `-manage-agent=false` and then using whatever tooling you wish to manage the daemonset.

I don't want an explosion of flags where all of the daemonset yaml options are slowly trickled up to operator options.

I've been bouncing around the idea of a TPR (CRD now I guess), or at least a config-map, which would be a more appropriate place for these sorts of customizations.

> As an aside, are there plans to make the tags consistent where the Deployment uses ':v0.2.0' and the DaemonSet uses ':0.2.0'

Everything should use `v` as of #71.

**Comment by dghubble** [comment]
Agreed, `-manage-agent=false` should be used here so you can make whatever changes are suitable for your cluster directly. As per #98, we'll be starting to think about managing/migration as the job of tooling or other components.

**Comment by dghubble** [comment]
Hopefully the updated [examples](examples) and usage doc showing creating a separate `update-operator` deployment and `update-agent` daemonset makes this more clear. Specifically, the agent example shows [tolerating a taint](https://github.com/coreos/container-linux-update-operator/blob/master/examples/update-agent.yaml.tmpl#L39) which we're conventionally applying on many clusters, but could be adapted to suit any custom needs or preferences.

Feel free to re-open if its unclear.
