### ISSUE TITLE
Add ability to verify health before continuing to next node

### ISSUE THREAD

**Issue by thrawn997** [coreos/container-linux-update-operator#99]
We recently used this operator and it seems like it reboots nodes too quickly - it doesn't wait until pods are ready before proceeding to the next node.  It would be good to either offer a health endpoint we can pass to let the operator know a node is up and ready, or do a check to see if there are any unready pods on the node that was just rebooted.  Right now we intend to write our own controller to check to see if there are any unhealthy pods and then set the paused annotation if there are any unready pods.

**Comment by lucab** [comment]
I think @robszumski mentioned a similar behavior would be useful to handle corner-cases where some heavy skews/incompatibilities happen between CL components (i.e. docker) and k8s versions (too-new OS with too-old k8s, or viceversa). Such a knob would allow to start OS upgrades in such case on some of the node nodes, but stopping it before affecting the cluster as a whole.

**Comment by thrawn997** [comment]
Another example would be the stack crash kernel update. It causes certain java applications to crash. The above proposal of checking for unready pods would limit the impact to a single node as opposed to causing a full outage.

**Comment by robszumski** [comment]
We need to think through if we should simply look at the node itself or pods on it. To be super defensive, I could see a situation where end-user pods cause the update to stop progressing, but that might not be desired. Happy to hear y'alls thoughts.

**Comment by thrawn997** [comment]
Yeah, but it could also enable some use cases that right now stop us from running certain workloads on CoreOS. Imagine running an HA setup of Vault or similar keystore. If a node reboots that is running Vault, it will require users to enter their passwords before it is ready. In the current state, all nodes would reboot without knowing this HA setup is degraded and take down the keystore. Similarly, if you need to have a certain number of database running at a time, but it takes those databases half an hour to warm and become ready, you could easily break the desired state of your cluster.  With this feature all those issues would be solved. You'd just need to alert on the cluster updates being paused until manual intervention. 

One way to resolve this is to know what version the cluster was on, capture what pods are currently not ready, and halt  updates until pods that where ready prior to the update are ready after the update.

**Comment by dghubble** [comment]
During a coordinated auto-update a chosen node should reboot and the operator should wait until that node returns and the update-agent pod starts and changes the node annotations so this encompasses Kubernetes' notion of Node Ready and also shows at least that agent pod was able to run. https://github.com/coreos/container-linux-update-operator/blob/master/pkg/operator/operator.go#L46

Judging node readiness (or another imaginary tier of readiness) based on whether the entire pod workload is running is plausible but has its own problems. We see this class of issue on cluster automation tests that try to require complete pod readiness:

* At what moment does update-agent check whether pods on the same node are healthy. It might be scheduled very early and no other pods are running so the check can be a NoOp based on timing.
* A single pod failing or having some issue is surprisingly common in steady state clusters when nobody is paying attention. Does that merit halting the auto-update rollout? Depends. You may be the operator and the app doesn't belong to your team.

**Comment by thrawn997** [comment]
My suggestion would be for the controller to store the os version and number of unready pods of a cluster. If a node updates, it keeps itself marked as paused until the controller verifies the new version didn't increases the number of faulty pods. If it does, provide notification hooks to email or webhook, or report it on the health status of the controller so that users can alert on it. 

And I'd imagine this would be an optional feature.

**Comment by dghubble** [comment]
What you describe is a broader issue that has been asked in different forms for a long time. Its one of the main challenges to building atop infrastructure with rolling updates - how to add safeguards for specific use-cases:

* locksmithd provided coordination and general system health checks
* cluo provides coordination and general Kubernetes node healthiness checks

When applications have specific healthiness definitions, you can write that custom logic and indicate to the system that an auto-update was not successful (_need to find those docs_). With locksmithd this was usually a systemd unit. In Kubernetes, we need to define that customization hook and when something goes into CLUO and when its custom.

> halt updates until pods that where ready prior to the update are ready after the update
> controller to store the os version and number of unready pods of a cluster

I see these as non-starters. Kubernetes state is constantly changing and reconciling. A snapshot of what was running before isn't associated with what will be running on the node after an update in the general case.

**Comment by robszumski** [comment]
> I see these as non-starters. Kubernetes state is constantly changing and reconciling. A snapshot of what was running before isn't associated with what will be running on the node after an update in the general case.

Agreed, in a highly dynamic cluster with a lot of automated CI/CD this will constantly change.

**Comment by thrawn997** [comment]
I think Kubernetes provides a good enough api to be able to infer that an update is causing unusually large numbers of errors. But luckily it seems like there's a fairly straightforward way for us to do this ourselves: add the paused annotation whenever our deployments are not fully available, and alert if that state remains for too long. Might not be the best logic, as it will pause and prevent updates when we deploy apps ,  but it should get us by.

**Comment by dghubble** [comment]
Updated my comment to note how people add custom health checks with systemd. Suggested the analog would be a user health check pod which is configured to run before the update-agent (through some means). You can do your own checks, decide the node is not healthy enough to your liking. Then either update-agent does run (halts the rollout) or receives the signal that a custom checker considered the node unhealthy and is able to trigger a rollback (new functionality).

**Comment by robszumski** [comment]
Should we include node draining into this converstation? Right now I believe use the kubelet to inform pods forcefully that they need to exit and use the kubelet's grace period. If we used the drain functionality in the API, this might hint to the scheduler more gracefully.

**Comment by lucab** [comment]
> the operator should wait until that node returns and the update-agent pod starts and changes the node annotations so this encompasses Kubernetes' notion of Node Ready and also shows at least that agent pod was able to run

Thanks for the note @dghubble, this is enough for my CL->docker->kubelet case.

**Comment by thrawn997** [comment]
Actually, if the agent stops the nose update if draining fails, that could solve my use case - I would just need to set a pod disruption budget in Kubernetes 1.7. Will the agent continue patching a node if draining fails?

**Comment by thrawn997** [comment]
The more I think about it, the more I think this is actually the same as https://github.com/coreos/container-linux-update-operator/issues/50

If pod disruption budget is set, per the document for Kubernetes a drain will fail. This is the proper signal that a reboot is not appropriate.

**Comment by dghubble** [comment]
Any interest in testing the new before-reboot and after-reboot required annotations in v0.3.0? https://github.com/coreos/container-linux-update-operator/blob/master/doc/before-after-reboot-checks.md

This feature allows you to write a custom health check that runs before a node is allowed to reboot or after a node has rebooted (but before its marked schedulable).

**Comment by thrawn997** [comment]
We're actually working on implementing that right now.  So far it seems like this completely solves our issue, but will let you know once we've tested fully. Thanks!

**Comment by dghubble** [comment]
Thanks! I'm closing for now since the feature is released. Feel free to re-open or file any issues!
